# Generated by Django 3.2.7 on 2021-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uteachilearnapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='app_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.IntegerField(),
        ),
    ]
