# Generated by Django 3.2.7 on 2021-09-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uteachilearnapi', '0003_auto_20210910_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savepost',
            old_name='app_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_on',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_date',
            field=models.IntegerField(),
        ),
    ]
