# Generated by Django 3.2.7 on 2021-09-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uteachilearnapi', '0005_auto_20210911_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_teacher',
        ),
    ]
