# Generated by Django 3.2.7 on 2021-09-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uteachilearnapi', '0009_auto_20210913_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='scheduler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to='uteachilearnapi.appuser'),
            preserve_default=False,
        ),
    ]
