# Generated by Django 3.2.7 on 2021-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uteachilearnapi', '0010_meeting_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_date',
            field=models.CharField(max_length=50),
        ),
    ]
