# Generated by Django 3.2.7 on 2021-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uteachilearnapi', '0014_alter_appuser_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='image_url',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
