# Generated by Django 4.1.2 on 2022-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uteachilearnapi", "0015_auto_20210922_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="bio",
            field=models.CharField(max_length=200),
        ),
    ]
